---
- name: copy up static files
  copy: src={{ src }} dest=/var/ owner=www-data

- name: create vhost
  template: src=static-vhost.j2 dest=/etc/nginx/sites-available/{{ hostname }}

- name: link vhost into place
  file: src=/etc/nginx/sites-available/{{ hostname }} dest=/etc/nginx/sites-enabled/{{ hostname }} state=link
  notify:
    - restart nginx
